name: Build and Push Docker Image Production
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker Image
      run: |
        docker build -t nlpo-dashboard .

    - name: Push Docker Image
      run: |
        docker tag nlpo-dashboard-old ghcr.io/eagerly-internet/nlpo-dashboard-old:latest
        docker push ghcr.io/eagerly-internet/nlpo-dashboard-old:latest
